// それぞれの名前にシングルかダブルクォートがあれば調整すること
function initSongs() {
    return [
        {artist: 'ボカロ',song: '1925',youtubeLinks: ['https://www.youtube.com/embed/HejWiGIA2rQ?start=4815',],uploadDate: '2024/04/23'},
        {artist: '宝鐘マリン - Vtuber',song: 'Ahoy!! 我ら宝鐘海賊団☆',youtubeLinks: ['https://www.youtube.com/embed/ZvC5W5wPHAM?start=2496','https://www.youtube.com/embed/dHWhaC2nexg?start=6513',],uploadDate: '2024/07/23'},
        {artist: '東方',song: 'Bad Apple!!',youtubeLinks: ['https://www.youtube.com/embed/ZvC5W5wPHAM?start=1735',],uploadDate: '2024/07/23'},
        {artist: 'Creepy Nuts - マッシュル',song: 'Bling-Bang-Bang-Born',youtubeLinks: ['https://www.youtube.com/embed/ROxeYUG6J8A?start=351','https://www.youtube.com/embed/0SpDxwXYsEM?start=7659','https://www.youtube.com/embed/2FSuC3sF7AY?start=874',],uploadDate: '2024/03/04'},
        {artist: '和田光司',song: 'Butter-Fly',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=2076',],uploadDate: '2023/06/05'},
        {artist: '放課後ティータイム - けいおん',song: 'Cagayake!GIRLS',youtubeLinks: ['https://www.youtube.com/embed/4uzfey2EOTc?start=5773',],uploadDate: '2024/12/20'},
        {artist: 'LiSA - SAO',song: 'Catch the Moment',youtubeLinks: ['https://www.youtube.com/embed/VpkfTbqCy_Y?start=3661',],uploadDate: '2024/09/24'},
        {artist: 'miwa - ブリーチ',song: 'chAngE',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=4015',],uploadDate: '2023/06/29'},
        {artist: 'ナナシス',song: "CHECK'MATE",youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=4885',],uploadDate: '2024/04/18'},
        {artist: 'ボカロ',song: 'Crazy∞nighT',youtubeLinks: ['https://www.youtube.com/embed/Lh2rxl1lWyI?start=4964',],uploadDate: '2024/10/29'},
        {artist: 'LiSA - SAO',song: 'crossing field',youtubeLinks: ['https://www.youtube.com/embed/B4QjGk-20OI?start=2836','https://www.youtube.com/embed/4uzfey2EOTc?start=1500',],uploadDate: '2024/07/12'},
        {artist: "u's - ラブライブ",song: 'Cutie Panther',youtubeLinks: ['https://www.youtube.com/embed/M95USmsYFO0?start=2399','https://www.youtube.com/embed/K9ppwMaarKs?start=1214','https://www.youtube.com/embed/Sy04TSlMgs8?start=1059',],uploadDate: '2023/04/14'},
        {artist: "u's - ラブライブ",song: 'Dancing stars on me!',youtubeLinks: ['https://www.youtube.com/embed/M95USmsYFO0?start=3823','https://www.youtube.com/embed/LMA1d775Qpk?start=2774','https://www.youtube.com/embed/Lh2rxl1lWyI?start=3520',],uploadDate: '2023/04/14'},
        {artist: 'プリキュア',song: 'DANZEN!ふたりはプリキュア',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=360','https://www.youtube.com/embed/Rfgv8LV1_3A?start=1507',],uploadDate: '2023/06/01'},
        {artist: 'EGOIST',song: 'Departures～あなたにおくるアイの歌～',youtubeLinks: ['https://www.youtube.com/embed/MGsqoEivfO4?start=1782','https://www.youtube.com/embed/itTI_e9fSPY?start=9921','https://www.youtube.com/embed/B4QjGk-20OI?start=7412',],uploadDate: '2023/03/28'},
        {artist: '放課後ティータイム - けいおん',song: "Don't say 'lazy'",youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=1937','https://www.youtube.com/embed/L0C7ddHFY8I?start=1506','https://www.youtube.com/embed/4uzfey2EOTc?start=6410',],uploadDate: '2023/04/10'},
        {artist: '水樹奈々',song: 'ETERNAL BLAZE',youtubeLinks: ['https://www.youtube.com/embed/4uzfey2EOTc?start=195',],uploadDate: '2024/12/20'},
        {artist: 'Superfly',song: 'Fall',youtubeLinks: ['https://www.youtube.com/embed/L0C7ddHFY8I?start=1990',],uploadDate: '2024/03/18'},
        {artist: 'EGOIST',song: 'Fallen',youtubeLinks: ['https://www.youtube.com/embed/urwa-ef1KOw?start=2909',],uploadDate: '2024/03/27'},
        {artist: '田村ゆかり',song: 'Fantastic future',youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=6551','https://www.youtube.com/embed/Rfgv8LV1_3A?start=230','https://www.youtube.com/embed/ROxeYUG6J8A?start=2428',],uploadDate: '2023/04/10'},
        {artist: 'The QUEEN of PURPLE',song: 'Fire and Rose',youtubeLinks: ['https://www.youtube.com/embed/ROxeYUG6J8A?start=6358',],uploadDate: '2024/03/04'},
        {artist: '米津玄師',song: 'Flamingo',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=2978',],uploadDate: '2023/05/19'},
        {artist: 'ナナシス',song: 'FUNBARE☆RUNNER',youtubeLinks: ['https://www.youtube.com/embed/BPTPA6mBPOM?start=4010',],uploadDate: '2023/07/13'},
        {artist: '放課後ティータイム - けいおん',song: 'GO!GO!MANIAC',youtubeLinks: ['https://www.youtube.com/embed/WmAQDaz2Lew?start=2958','https://www.youtube.com/embed/VpkfTbqCy_Y?start=875',],uploadDate: '2023/10/24'},
        {artist: '涼宮ハルヒの憂鬱',song: 'God Knows...',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=347','https://www.youtube.com/embed/0EYG1N-wegA?start=1206','https://www.youtube.com/embed/B4QjGk-20OI?start=1742',],uploadDate: '2023/06/09'},
        {artist: 'ナナシス',song: 'H-A-J-I-M-A-R-I-U-T-A-!!',youtubeLinks: ['https://www.youtube.com/embed/E_gzQSl55W4?start=2954',],uploadDate: '2024/05/23'},
        {artist: 'Aqours - ラブライブ',song: 'HAPPY PARTY TRAIN',youtubeLinks: ['https://www.youtube.com/embed/E_gzQSl55W4?start=1077','https://www.youtube.com/embed/rDor8WLUz3k?start=240',],uploadDate: '2024/05/23'},
        {artist: 'ナナシス',song: 'Hello...my friend',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=2171',],uploadDate: '2024/04/18'},
        {artist: 'ビートまりお',song: 'Help me,ERINNNNNN!!',youtubeLinks: ['https://www.youtube.com/embed/ZvC5W5wPHAM?start=2304',],uploadDate: '2024/07/23'},
        {artist: 'T.M.Revolution - 西川貴教',song: 'HOT LIMIT',youtubeLinks: ['https://www.youtube.com/embed/G7eO7CrCnXY?start=6234','https://www.youtube.com/embed/GEQLbX0qVmY?start=4282','https://www.youtube.com/embed/wl2b0DRtLE0?start=6250',],uploadDate: '2023/09/14'},
        {artist: 'ボカロ',song: 'Just Be Friends',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=7727','https://www.youtube.com/embed/ep2iRkJXY-4?start=6194',],uploadDate: '2023/06/29'},
        {artist: 'EGOIST - 甲鉄城のカバネリ',song: 'KABANERI OF THE IRON FORTRESS',youtubeLinks: ['https://www.youtube.com/embed/m101bPhdXKA?start=3085',],uploadDate: '2024/04/08'},
        {artist: '米津玄師',song: 'KICK BACK',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=1773','https://www.youtube.com/embed/WXIN8Ip0X10?start=2090','https://www.youtube.com/embed/LMA1d775Qpk?start=1397',],uploadDate: '2023/05/19'},
        {artist: 'ボカロ',song: 'KING',youtubeLinks: ['https://www.youtube.com/embed/-9EbEyxBdxc?start=4263','https://www.youtube.com/embed/Lh2rxl1lWyI?start=1940',],uploadDate: '2024/05/16'},
        {artist: 'ぴちぴちピッチ',song: 'Legend of Mermaid',youtubeLinks: ['https://www.youtube.com/embed/IXqpbXYPpBc?start=2795',],uploadDate: '2024/01/11'},
        {artist: '米津玄師',song: 'Lemon',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=3410','https://www.youtube.com/embed/td1q0jB1olk?start=3312','https://www.youtube.com/embed/Lh2rxl1lWyI?start=6342',],uploadDate: '2023/05/19'},
        {artist: '米津玄師',song: 'LOSER',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=315','https://www.youtube.com/embed/WXIN8Ip0X10?start=1360',],uploadDate: '2023/05/19'},
        {artist: "u's - ラブライブ",song: 'Love marginal',youtubeLinks: ['https://www.youtube.com/embed/Sy04TSlMgs8?start=1884',],uploadDate: '2024/04/03'},
        {artist: '嵐',song: 'Love so Sweet',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=8018',],uploadDate: '2023/06/29'},
        {artist: 'ナナシス',song: 'Lucky☆Lucky',youtubeLinks: ['https://www.youtube.com/embed/ROxeYUG6J8A?start=5965',],uploadDate: '2024/03/04'},
        {artist: 'ボカロ',song: 'magnet',youtubeLinks: ['https://www.youtube.com/embed/pNj4jJbUW4o?start=2046',],uploadDate: '2024/02/21'},
        {artist: '緑黄色社会',song: 'Mela!',youtubeLinks: ['https://www.youtube.com/embed/9Fj9vYgzL6c?start=4470','https://www.youtube.com/embed/L0C7ddHFY8I?start=283',],uploadDate: '2023/07/29'},
        {artist: '嵐',song: 'Monster',youtubeLinks: ['https://www.youtube.com/embed/Lh2rxl1lWyI?start=4487',],uploadDate: '2024/10/29'},
        {artist: '倖田來未',song: 'Moon Crying',youtubeLinks: ['https://www.youtube.com/embed/pNj4jJbUW4o?start=2648',],uploadDate: '2024/02/21'},
        {artist: 'ボカロ',song: 'Mrs. Pumpkinの滑稽な夢',youtubeLinks: ['https://www.youtube.com/embed/WmAQDaz2Lew?start=1953','https://www.youtube.com/embed/2FSuC3sF7AY?start=2069',],uploadDate: '2023/10/24'},
        {artist: "u's - ラブライブ",song: 'Music S.T.A.R.T!!',youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=285','https://www.youtube.com/embed/mADbrQhuOik?start=5780','https://www.youtube.com/embed/rDor8WLUz3k?start=2149',],uploadDate: '2023/04/10'},
        {artist: 'Supercell',song: 'MyDearest',youtubeLinks: ['https://www.youtube.com/embed/MGsqoEivfO4?start=1046',],uploadDate: '2023/03/28'},
        {artist: '米津玄師',song: 'M八七',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=6607','https://www.youtube.com/embed/4uzfey2EOTc?start=6915',],uploadDate: '2023/05/19'},
        {artist: "u's - ラブライブ",song: 'No brand girls',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=10203','https://www.youtube.com/embed/rDor8WLUz3k?start=1060',],uploadDate: '2023/06/29'},
        {artist: "u's - ラブライブ",song: 'NO EXIT ORION',youtubeLinks: ['https://www.youtube.com/embed/Sy04TSlMgs8?start=1450','https://www.youtube.com/embed/ZvC5W5wPHAM?start=1236',],uploadDate: '2024/04/03'},
        {artist: 'ボカロ',song: 'ODDS＆ENDS',youtubeLinks: ['https://www.youtube.com/embed/pS2dYFRWMuU?start=3985',],uploadDate: '2024/05/09'},
        {artist: 'fripSide - 超電磁砲',song: 'only my railgun',youtubeLinks: ['https://www.youtube.com/embed/cpMWJrh1t-k?start=451','https://www.youtube.com/embed/LMA1d775Qpk?start=5556',],uploadDate: '2023/11/09'},
        {artist: '大塚愛',song: 'PEACH',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=7037',],uploadDate: '2024/04/18'},
        {artist: '推しの子',song: 'POP IN 2',youtubeLinks: ['https://www.youtube.com/embed/wl2b0DRtLE0?start=4600','https://www.youtube.com/embed/NavZce1Abng?start=2405',],uploadDate: '2024/11/27'},
        {artist: "u's - ラブライブ",song: 'PSYCHIC FIRE',youtubeLinks: ['https://www.youtube.com/embed/urwa-ef1KOw?start=396','https://www.youtube.com/embed/wZNw01A2ZPU?start=1260',],uploadDate: '2024/03/27'},
        {artist: 'ボカロ',song: 'RIP=RELEASE',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=7169',],uploadDate: '2023/04/17'},
        {artist: 'ナナシス',song: 'SAKURA',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=4120',],uploadDate: '2024/04/18'},
        {artist: 'ZONE',song: 'secret base～君がくれたもの～',youtubeLinks: ['https://www.youtube.com/embed/9Fj9vYgzL6c?start=470','https://www.youtube.com/embed/-9EbEyxBdxc?start=4757','https://www.youtube.com/embed/_rAdBgHFFjU?start=1174',],uploadDate: '2023/07/29'},
        {artist: 'ナナシス',song: 'SEVENTH HAVEN',youtubeLinks: ['https://www.youtube.com/embed/ROxeYUG6J8A?start=5727',],uploadDate: '2024/03/04'},
        {artist: 'ナナシス',song: 'SHAKE!!～フリフリしちゃえ～',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=8458',],uploadDate: '2024/04/18'},
        {artist: '唐沢 美帆 - ヴァイオレット・エヴァーガーデン',song: 'Sincerely',youtubeLinks: ['https://www.youtube.com/embed/VsFaoOFt0_0?start=6002','https://www.youtube.com/embed/bKJWgs1AaDc?start=1950','https://www.youtube.com/embed/NOirh8vHd2I?start=991',],uploadDate: '2023/08/05'},
        {artist: "u's - ラブライブ",song: 'Snow halation',youtubeLinks: ['https://www.youtube.com/embed/WXIN8Ip0X10?start=2474','https://www.youtube.com/embed/-9EbEyxBdxc?start=1827','https://www.youtube.com/embed/LMA1d775Qpk?start=2000',],uploadDate: '2024/02/01'},
        {artist: 'ナナシス',song: 'Snow in "I love you"',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=1333',],uploadDate: '2024/04/18'},
        {artist: "u's - ラブライブ",song: 'START:DASH!!',youtubeLinks: ['https://www.youtube.com/embed/MGsqoEivfO4?start=470','https://www.youtube.com/embed/E_gzQSl55W4?start=639','https://www.youtube.com/embed/rDor8WLUz3k?start=655',],uploadDate: '2023/03/28'},
        {artist: 'Aqours - ラブライブ',song: 'Strawberry Trapper',youtubeLinks: ['https://www.youtube.com/embed/QPusrCYYy3c?start=5685',],uploadDate: '2024/08/01'},
        {artist: 'アイマス',song: 'Study Equal Magic!',youtubeLinks: ['https://www.youtube.com/embed/-9EbEyxBdxc?start=2468',],uploadDate: '2024/05/16'},
        {artist: 'ギルティクラウン',song: 'The Everlasting Guilty Crown',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=3852','https://www.youtube.com/embed/4Jrfzxmt3Z8?start=12232','https://www.youtube.com/embed/NavZce1Abng?start=6829',],uploadDate: '2023/06/09'},
        {artist: "u's - ラブライブ",song: 'Tiny Stars',youtubeLinks: ['https://www.youtube.com/embed/AmxKWJq9Utc?start=387',],uploadDate: '2024/07/27'},
        {artist: 'Ado - ワンピース',song: 'Tot Musica',youtubeLinks: ['https://www.youtube.com/embed/wpv_uWc3HGg?start=677',],uploadDate: '2024/05/16'},
        {artist: 'アイマス',song: 'Trancing Pulse',youtubeLinks: ['https://www.youtube.com/embed/wZNw01A2ZPU?start=673',],uploadDate: '2024/06/11'},
        {artist: 'ナナシス',song: 'TREAT OR TREAT?',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=1809','https://www.youtube.com/embed/2FSuC3sF7AY?start=4451',],uploadDate: '2024/04/18'},
        {artist: '放課後ティータイム - けいおん',song: 'U&I',youtubeLinks: ['https://www.youtube.com/embed/VpkfTbqCy_Y?start=1600',],uploadDate: '2024/09/24'},
        {artist: 'OxT（オーイシマサヨシ・Tom-H@ck）',song: 'UNION',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=4481','https://www.youtube.com/embed/ROxeYUG6J8A?start=3142','https://www.youtube.com/embed/4uzfey2EOTc?start=686',],uploadDate: '2023/06/13'},
        {artist: 'ウマ娘',song: 'winning the soul',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=9713','https://www.youtube.com/embed/kgRYm7SUMqM?start=5806',],uploadDate: '2023/06/29'},
        {artist: "u's - ラブライブ",song: 'Wonderful Rush',youtubeLinks: ['https://www.youtube.com/embed/BPTPA6mBPOM?start=265',],uploadDate: '2023/07/13'},
        {artist: 'いきものがかり',song: 'YELL',youtubeLinks: ['https://www.youtube.com/embed/itTI_e9fSPY?start=4753',],uploadDate: '2023/12/01'},
        {artist: 'アイマス',song: 'Yes!Party Time!!',youtubeLinks: ['https://www.youtube.com/embed/wZNw01A2ZPU?start=4278',],uploadDate: '2024/06/11'},
        {artist: 'ナナシス',song: "You Can't Win",youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=4550',],uploadDate: '2024/04/18'},
        {artist: '学マス - アイマス',song: 'アイヴイ',youtubeLinks: ['https://www.youtube.com/embed/dHWhaC2nexg?start=941',],uploadDate: '2024/09/10'},
        {artist: 'YOASOBI - 推しの子',song: 'アイドル',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=2537','https://www.youtube.com/embed/4Jrfzxmt3Z8?start=3847','https://www.youtube.com/embed/4uzfey2EOTc?start=4590',],uploadDate: '2023/06/01'},
        {artist: '米津玄師',song: 'アイネクライネ',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=7041','https://www.youtube.com/embed/WXIN8Ip0X10?start=983','https://www.youtube.com/embed/_rAdBgHFFjU?start=4624',],uploadDate: '2023/05/19'},
        {artist: '湊あくあ - Vtuber',song: 'あくあ色ぱれっと',youtubeLinks: ['https://www.youtube.com/embed/JUZ_ABhOoDM?start=1570',],uploadDate: '2024/10/26'},
        {artist: '湊あくあ - Vtuber',song: 'あくたんのこと好きすぎ☆ソング',youtubeLinks: ['https://www.youtube.com/embed/JUZ_ABhOoDM?start=205','https://www.youtube.com/embed/Lh2rxl1lWyI?start=608',],uploadDate: '2024/10/26'},
        {artist: 'ポルノグラフィティ',song: 'アゲハ蝶',youtubeLinks: ['https://www.youtube.com/embed/L0C7ddHFY8I?start=8023',],uploadDate: '2024/03/18'},
        {artist: 'Ado',song: 'アタシは問題作',youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=3389','https://www.youtube.com/embed/WmAQDaz2Lew?start=3493','https://www.youtube.com/embed/_rAdBgHFFjU?start=1701',],uploadDate: '2023/04/10'},
        {artist: 'YOASOBI',song: 'あの夢をなぞって',youtubeLinks: ['https://www.youtube.com/embed/9Fj9vYgzL6c?start=6226',],uploadDate: '2023/07/29'},
        {artist: 'アイマス',song: 'あんずのうた',youtubeLinks: ['https://www.youtube.com/embed/E_gzQSl55W4?start=2515',],uploadDate: '2024/05/23'},
        {artist: 'ディズニー',song: 'アンダー・ザ・シー',youtubeLinks: ['https://www.youtube.com/embed/VsFaoOFt0_0?start=3556','https://www.youtube.com/embed/Rfgv8LV1_3A?start=5082','https://www.youtube.com/embed/dHWhaC2nexg?start=3541',],uploadDate: '2023/08/05'},
        {artist: 'その他',song: 'アンパンマンのマーチ',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=8363',],uploadDate: '2023/06/29'},
        {artist: 'その他',song: 'いぬのおまわりさん',youtubeLinks: ['https://www.youtube.com/embed/WmAQDaz2Lew?start=5633',],uploadDate: '2023/10/24'},
        {artist: 'ボカロ',song: 'ヴァンパイア',youtubeLinks: ['https://www.youtube.com/embed/itTI_e9fSPY?start=2261','https://www.youtube.com/embed/Lh2rxl1lWyI?start=1628',],uploadDate: '2023/12/01'},
        {artist: 'きただにひろし - ワンピース',song: 'ウィーアー!',youtubeLinks: ['https://www.youtube.com/embed/LMA1d775Qpk?start=3216',],uploadDate: '2024/10/15'},
        {artist: 'Ado - ワンピース',song: 'ウタカタララバイ',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=1885','https://www.youtube.com/embed/eALWj0vtpYQ?start=5656','https://www.youtube.com/embed/ROxeYUG6J8A?start=988',],uploadDate: '2023/06/09'},
        {artist: 'Ado',song: 'うっせえわ',youtubeLinks: ['https://www.youtube.com/embed/WmAQDaz2Lew?start=5138',],uploadDate: '2023/10/24'},
        {artist: 'ウマ娘',song: 'うまぴょい伝説',youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=2578','https://www.youtube.com/embed/eALWj0vtpYQ?start=1463','https://www.youtube.com/embed/4YmHDjaNqxQ?start=1484',],uploadDate: '2023/04/10'},
        {artist: 'ボカロ',song: 'え？あぁ、そう。',youtubeLinks: ['https://www.youtube.com/embed/pNj4jJbUW4o?start=1631',],uploadDate: '2024/02/21'},
        {artist: 'その他 - 太鼓の達人',song: 'エンジェル ドリーム',youtubeLinks: ['https://www.youtube.com/embed/E_gzQSl55W4?start=2109',],uploadDate: '2024/05/23'},
        {artist: 'おジャ魔女どれみ',song: 'おジャ魔女カーニバル!!',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=7985','https://www.youtube.com/embed/LMA1d775Qpk?start=4635',],uploadDate: '2023/06/01'},
        {artist: '新しい学校のリーダーズ',song: 'オトナブルー',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=6518',],uploadDate: '2023/06/05'},
        {artist: 'ダンベル何キロ持てる?',song: 'おねがいマッスル',youtubeLinks: ['https://www.youtube.com/embed/cpMWJrh1t-k?start=6190',],uploadDate: '2023/11/09'},
        {artist: 'その他',song: 'おばけなんてないさ',youtubeLinks: ['https://www.youtube.com/embed/Lh2rxl1lWyI?start=5433',],uploadDate: '2024/10/29'},
        {artist: 'その他',song: 'およげ!たいきやきくん',youtubeLinks: ['https://www.youtube.com/embed/TUvA7zIr1KM?start=7732',],uploadDate: '2024/02/27'},
        {artist: '米津玄師',song: 'カナリヤ',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=6340','https://www.youtube.com/embed/Lh2rxl1lWyI?start=6865',],uploadDate: '2024/04/18'},
        {artist: 'ボカロ',song: 'からくりピエロ',youtubeLinks: ['https://www.youtube.com/embed/itTI_e9fSPY?start=1458',],uploadDate: '2023/12/01'},
        {artist: '放課後ティータイム - けいおん',song: 'カレーのちライス',youtubeLinks: ['https://www.youtube.com/embed/VpkfTbqCy_Y?start=1270',],uploadDate: '2024/09/24'},
        {artist: 'GReeeeN - GRe4N BOYZ',song: 'キセキ',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=4475',],uploadDate: '2023/06/29'},
        {artist: 'ボカロ',song: 'キャットラビング',youtubeLinks: ['https://www.youtube.com/embed/K9ppwMaarKs?start=4460','https://www.youtube.com/embed/MAcwKdfs5qQ?start=4821',],uploadDate: '2023/10/30'},
        {artist: 'キューティーハニー',song: 'キューティーハニー',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=6921','https://www.youtube.com/embed/pNj4jJbUW4o?start=3285','https://www.youtube.com/embed/wZNw01A2ZPU?start=2876',],uploadDate: '2023/06/05'},
        {artist: 'Ado',song: 'ギラギラ',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=3387','https://www.youtube.com/embed/bKJWgs1AaDc?start=3964','https://www.youtube.com/embed/_rAdBgHFFjU?start=1976',],uploadDate: '2023/06/09'},
        {artist: 'その他',song: 'キリンレモンのうた',youtubeLinks: ['https://www.youtube.com/embed/td1q0jB1olk?start=3188',],uploadDate: '2024/03/13'},
        {artist: '神宿',song: 'グリズリーに襲われたら',youtubeLinks: ['https://www.youtube.com/embed/E_gzQSl55W4?start=1532',],uploadDate: '2024/05/23'},
        {artist: 'ボカロ',song: 'クワガタにチョップしたらタイムスリップした',youtubeLinks: ['https://www.youtube.com/embed/L0C7ddHFY8I?start=9106',],uploadDate: '2024/03/18'},
        {artist: 'ケロロ軍曹',song: 'ケロッ!とマーチ',youtubeLinks: ['https://www.youtube.com/embed/UjTKs05Icag?start=4138','https://www.youtube.com/embed/bFIhXKqst4E?start=5203','https://www.youtube.com/embed/4Jrfzxmt3Z8?start=11162',],uploadDate: '2023/05/09'},
        {artist: '米津玄師',song: 'ゴーゴー幽霊船',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=1260',],uploadDate: '2023/05/19'},
        {artist: 'ボカロ',song: 'こっち向いてBaby',youtubeLinks: ['https://www.youtube.com/embed/MGsqoEivfO4?start=2661',],uploadDate: '2023/03/28'},
        {artist: 'Aqours - ラブライブ',song: 'コットンキャンディえいえいおー!',youtubeLinks: ['https://www.youtube.com/embed/urwa-ef1KOw?start=818','https://www.youtube.com/embed/ZvC5W5wPHAM?start=3323',],uploadDate: '2024/03/27'},
        {artist: 'ClariS - まどマギ',song: 'コネクト',youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=4330','https://www.youtube.com/embed/IXqpbXYPpBc?start=1118','https://www.youtube.com/embed/LMA1d775Qpk?start=3910',],uploadDate: '2023/04/10'},
        {artist: 'Aqours - ラブライブ',song: 'コワレヤスキ',youtubeLinks: ['https://www.youtube.com/embed/QPusrCYYy3c?start=6000',],uploadDate: '2024/08/01'},
        {artist: 'ディズニー',song: 'コンパス・オブ・ユア・ハート',youtubeLinks: ['https://www.youtube.com/embed/dHWhaC2nexg?start=5924','https://www.youtube.com/embed/dHWhaC2nexg?start=6170',],uploadDate: '2024/09/10'},
        {artist: '櫻坂46',song: 'サイレントマジョリティー',youtubeLinks: ['https://www.youtube.com/embed/Snfv7YDOjUE?start=1206',],uploadDate: '2024/01/17'},
        {artist: '推しの子',song: 'サインはB',youtubeLinks: ['https://www.youtube.com/embed/VsFaoOFt0_0?start=318','https://www.youtube.com/embed/_rAdBgHFFjU?start=2517','https://www.youtube.com/embed/BUDtEGiLhMw?start=270',],uploadDate: '2023/08/05'},
        {artist: 'ポルノグラフィティ',song: 'サウダージ',youtubeLinks: ['https://www.youtube.com/embed/bKJWgs1AaDc?start=4406',],uploadDate: '2024/01/06'},
        {artist: '大塚愛',song: 'さくらんぼ',youtubeLinks: ['https://www.youtube.com/embed/L0C7ddHFY8I?start=7497',],uploadDate: '2024/03/18'},
        {artist: 'supercell',song: 'さよならメモリーズ',youtubeLinks: ['https://www.youtube.com/embed/td1q0jB1olk?start=7784','https://www.youtube.com/embed/MGlP_G5zu0I?start=1119',],uploadDate: '2024/03/13'},
        {artist: '血界戦線',song: 'シュガーソングとビターステップ',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=4314','https://www.youtube.com/embed/MAcwKdfs5qQ?start=5938','https://www.youtube.com/embed/VpkfTbqCy_Y?start=345',],uploadDate: '2023/06/09'},
        {artist: 'P丸様 - Vtuber',song: 'シル・ヴ・プレジデント',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=8670','https://www.youtube.com/embed/BUDtEGiLhMw?start=4871','https://www.youtube.com/embed/VpkfTbqCy_Y?start=2005',],uploadDate: '2023/06/01'},
        {artist: 'KANA-BOON - ナルト',song: 'シルエット',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=5398','https://www.youtube.com/embed/ROxeYUG6J8A?start=4104','https://www.youtube.com/embed/9qJ_Ec2YxSk?start=932',],uploadDate: '2023/06/09'},
        {artist: 'Aqours - ラブライブ',song: 'スリリング・ワンウェイ',youtubeLinks: ['https://www.youtube.com/embed/B4QjGk-20OI?start=322','https://www.youtube.com/embed/AmxKWJq9Utc?start=975',],uploadDate: '2024/07/12'},
        {artist: 'ボカロ',song: 'セツナトリップ',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=2901','https://www.youtube.com/embed/m101bPhdXKA?start=1311',],uploadDate: '2023/04/17'},
        {artist: 'JUDY AND MARY - るろ剣',song: 'そばかす',youtubeLinks: ['https://www.youtube.com/embed/LMA1d775Qpk?start=6659',],uploadDate: '2024/10/15'},
        {artist: 'ヨルシカ',song: 'ただ君に晴れ',youtubeLinks: ['https://www.youtube.com/embed/Rfgv8LV1_3A?start=696',],uploadDate: '2023/12/10'},
        {artist: '岩崎良美 - タッチ',song: 'タッチ',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=9119','https://www.youtube.com/embed/pS2dYFRWMuU?start=697',],uploadDate: '2023/06/29'},
        {artist: 'きらりん☆レボリューション',song: 'チャンス!',youtubeLinks: ['https://www.youtube.com/embed/m101bPhdXKA?start=6576',],uploadDate: '2024/04/08'},
        {artist: 'きゃりーぱみゅぱみゅ',song: 'つけまつける',youtubeLinks: ['https://www.youtube.com/embed/0EYG1N-wegA?start=8975',],uploadDate: '2023/12/04'},
        {artist: 'ボカロ',song: 'デーモンロード',youtubeLinks: ['https://www.youtube.com/embed/wpv_uWc3HGg?start=308','https://www.youtube.com/embed/Lh2rxl1lWyI?start=2386',],uploadDate: '2024/05/16'},
        {artist: 'ボカロ',song: 'デビルじゃないもん',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=5521','https://www.youtube.com/embed/WmAQDaz2Lew?start=909',],uploadDate: '2023/04/17'},
        {artist: '米津玄師',song: 'ドーナツホール',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=2510','https://www.youtube.com/embed/ep2iRkJXY-4?start=4590','https://www.youtube.com/embed/2FSuC3sF7AY?start=2472',],uploadDate: '2023/05/19'},
        {artist: 'ハム太郎',song: 'とっとこハム太郎とっとこうた',youtubeLinks: ['https://www.youtube.com/embed/LMA1d775Qpk?start=4405',],uploadDate: '2024/10/15'},
        {artist: '優里',song: 'ドライフラワー',youtubeLinks: ['https://www.youtube.com/embed/bKJWgs1AaDc?start=707','https://www.youtube.com/embed/ZvC5W5wPHAM?start=4577','https://www.youtube.com/embed/MGlP_G5zu0I?start=480',],uploadDate: '2024/01/06'},
        {artist: 'ドラえもん',song: 'ドラえもんのうた',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=1063',],uploadDate: '2023/06/05'},
        {artist: 'その他',song: 'どんぐりころころ',youtubeLinks: ['https://www.youtube.com/embed/WmAQDaz2Lew?start=7395',],uploadDate: '2023/10/24'},
        {artist: 'KANA-BOON',song: 'ないものねだり',youtubeLinks: ['https://www.youtube.com/embed/WmAQDaz2Lew?start=6814','https://www.youtube.com/embed/ROxeYUG6J8A?start=5111',],uploadDate: '2023/10/24'},
        {artist: 'ディズニー',song: 'パート・オブ・ユア・ワールド',youtubeLinks: ['https://www.youtube.com/embed/9Fj9vYgzL6c?start=1533','https://www.youtube.com/embed/Rfgv8LV1_3A?start=5409',],uploadDate: '2023/07/29'},
        {artist: 'こっちのけんと',song: 'はいよころんで',youtubeLinks: ['https://www.youtube.com/embed/NavZce1Abng?start=4592','https://www.youtube.com/embed/dHWhaC2nexg?start=1439','https://www.youtube.com/embed/2FSuC3sF7AY?start=1248',],uploadDate: '2024/12/03'},
        {artist: '一青窈',song: 'ハナミズキ',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=4840',],uploadDate: '2023/06/29'},
        {artist: 'きらりん☆レボリューション',song: 'パパンケーキ',youtubeLinks: ['https://www.youtube.com/embed/m101bPhdXKA?start=6404',],uploadDate: '2024/04/08'},
        {artist: 'ハム太郎',song: 'ハム太郎とっとこうた',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=590','https://www.youtube.com/embed/MAcwKdfs5qQ?start=6385','https://www.youtube.com/embed/-9EbEyxBdxc?start=2933',],uploadDate: '2023/06/05'},
        {artist: 'ボカロ',song: 'パラジクロロベンゼン',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=6621',],uploadDate: '2023/04/17'},
        {artist: 'きらりん☆レボリューション',song: 'バラライカ',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=4073','https://www.youtube.com/embed/m101bPhdXKA?start=7480','https://www.youtube.com/embed/LMA1d775Qpk?start=6879',],uploadDate: '2023/06/13'},
        {artist: '涼宮ハルヒの憂鬱',song: 'ハレ晴レユカイ',youtubeLinks: ['https://www.youtube.com/embed/UjTKs05Icag?start=410','https://www.youtube.com/embed/tjOawBPYPV8?start=2024','https://www.youtube.com/embed/dHWhaC2nexg?start=5359',],uploadDate: '2023/05/09'},
        {artist: '米津玄師',song: 'ピースサイン',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=5605','https://www.youtube.com/embed/bKJWgs1AaDc?start=2380','https://www.youtube.com/embed/ROxeYUG6J8A?start=3807',],uploadDate: '2023/05/19'},
        {artist: '米津玄師',song: 'ひまわり',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=6140',],uploadDate: '2023/05/19'},
        {artist: 'ナナシス',song: 'ひまわりのストーリー',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=809',],uploadDate: '2024/04/18'},
        {artist: '秦基博',song: 'ひまわりの約束',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=2955','https://www.youtube.com/embed/HejWiGIA2rQ?start=799','https://www.youtube.com/embed/wl2b0DRtLE0?start=3661',],uploadDate: '2023/06/13'},
        {artist: 'ヒャダイン - 日常',song: 'ヒャダインのじょーじょーゆーじょー',youtubeLinks: ['https://www.youtube.com/embed/BUDtEGiLhMw?start=4355',],uploadDate: '2024/01/24'},
        {artist: 'がっこうぐらし!',song: 'ふ・れ・ん・ど・し・た・い',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=880','https://www.youtube.com/embed/VsFaoOFt0_0?start=2943','https://www.youtube.com/embed/4uzfey2EOTc?start=5172',],uploadDate: '2023/06/01'},
        {artist: 'mona - HoneyWorks',song: 'ファンサ',youtubeLinks: ['https://www.youtube.com/embed/4Jrfzxmt3Z8?start=9015',],uploadDate: '2024/04/30'},
        {artist: 'ボカロ',song: 'フォニィ',youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=6153','https://www.youtube.com/embed/bFIhXKqst4E?start=3434','https://www.youtube.com/embed/QPusrCYYy3c?start=880',],uploadDate: '2023/04/10'},
        {artist: 'CHiCO - HoneyWorks',song: 'プライド',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=8705',],uploadDate: '2023/06/29'},
        {artist: 'CHiCO - HoneyWorks',song: 'プライド革命',youtubeLinks: ['https://www.youtube.com/embed/Sy04TSlMgs8?start=3514',],uploadDate: '2024/04/03'},
        {artist: 'プリキュア',song: 'プリキュア5、スマイル go go!',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=5881','https://www.youtube.com/embed/Rfgv8LV1_3A?start=2490',],uploadDate: '2023/06/05'},
        {artist: "u's - ラブライブ",song: 'ぶる〜べりぃ♡とれいん',youtubeLinks: ['https://www.youtube.com/embed/urwa-ef1KOw?start=4428',],uploadDate: '2024/03/27'},
        {artist: 'いきものがかり - ナルト',song: 'ブルーバード',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=4842','https://www.youtube.com/embed/WXIN8Ip0X10?start=3735','https://www.youtube.com/embed/2FSuC3sF7AY?start=5885',],uploadDate: '2023/06/09'},
        {artist: "u's - ラブライブ",song: 'ぷわぷわーお!',youtubeLinks: ['https://www.youtube.com/embed/Sy04TSlMgs8?start=2416',],uploadDate: '2024/04/03'},
        {artist: '放課後ティータイム - けいおん',song: 'ふわふわ時間',youtubeLinks: ['https://www.youtube.com/embed/UjTKs05Icag?start=930','https://www.youtube.com/embed/mADbrQhuOik?start=1100',],uploadDate: '2023/05/09'},
        {artist: '優里',song: 'ベテルギウス',youtubeLinks: ['https://www.youtube.com/embed/DlJV7X5Wn90?start=2781','https://www.youtube.com/embed/1BOX2cFBGkw?start=293','https://www.youtube.com/embed/GEQLbX0qVmY?start=723',],uploadDate: '2023/10/17'},
        {artist: 'ボカロ',song: 'ボルテッカー',youtubeLinks: ['https://www.youtube.com/embed/K9ppwMaarKs?start=4840','https://www.youtube.com/embed/0EYG1N-wegA?start=2969','https://www.youtube.com/embed/MAcwKdfs5qQ?start=2405',],uploadDate: '2023/10/30'},
        {artist: '坂本真綾',song: 'マジックナンバー',youtubeLinks: ['https://www.youtube.com/embed/4uzfey2EOTc?start=2025',],uploadDate: '2024/12/20'},
        {artist: '松平健',song: 'マツケンサンバ',youtubeLinks: ['https://www.youtube.com/embed/NOirh8vHd2I?start=3826',],uploadDate: '2024/01/29'},
        {artist: 'ボカロ',song: 'マトリョシカ',youtubeLinks: ['https://www.youtube.com/embed/2FSuC3sF7AY?start=2835','https://www.youtube.com/embed/Lh2rxl1lWyI?start=5649',],uploadDate: '2024/10/02'},
        {artist: 'ボカロ',song: 'みくみくにしてあげる♪【してやんよ】',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=1453',],uploadDate: '2023/06/01'},
        {artist: 'ディズニー',song: 'ミッキーマウス・マーチ',youtubeLinks: ['https://www.youtube.com/embed/HejWiGIA2rQ?start=4352',],uploadDate: '2024/04/23'},
        {artist: 'Official髭男dism - スパイファミリー',song: 'ミックスナッツ',youtubeLinks: ['https://www.youtube.com/embed/WXIN8Ip0X10?start=178',],uploadDate: '2024/02/01'},
        {artist: 'ナナシス',song: 'ミツバチ',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=316','https://www.youtube.com/embed/4Jrfzxmt3Z8?start=6339',],uploadDate: '2024/04/18'},
        {artist: 'セーラームーン',song: 'ムーンライト伝説',youtubeLinks: ['https://www.youtube.com/embed/MGsqoEivfO4?start=3874',],uploadDate: '2023/03/28'},
        {artist: 'ポケモン',song: 'めざせポケモンマスター',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=2315','https://www.youtube.com/embed/dmNa1uamvDc?start=772','https://www.youtube.com/embed/m101bPhdXKA?start=5787',],uploadDate: '2023/06/05'},
        {artist: 'ボカロ',song: 'メズマライザー',youtubeLinks: ['https://www.youtube.com/embed/B4QjGk-20OI?start=4711',],uploadDate: '2024/07/12'},
        {artist: '女王蜂',song: 'メフィスト',youtubeLinks: ['https://www.youtube.com/embed/4Jrfzxmt3Z8?start=6232',],uploadDate: '2024/04/30'},
        {artist: 'ボカロ',song: 'モア!ジャンプ!モア!',youtubeLinks: ['https://www.youtube.com/embed/Sy04TSlMgs8?start=273','https://www.youtube.com/embed/E_gzQSl55W4?start=299',],uploadDate: '2024/04/03'},
        {artist: 'ボカロ',song: 'モザイクロール',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=4858',],uploadDate: '2023/04/17'},
        {artist: 'らき☆すた',song: 'もってけ!セーラーふく',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=4300','https://www.youtube.com/embed/cpMWJrh1t-k?start=4525','https://www.youtube.com/embed/B4QjGk-20OI?start=2142',],uploadDate: '2023/06/01'},
        {artist: '荒井由実 - ジブリ',song: 'やさしさに包まれたなら',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=1769',],uploadDate: '2023/06/29'},
        {artist: "u's - ラブライブ",song: 'ユメノトビラ',youtubeLinks: ['https://www.youtube.com/embed/AmxKWJq9Utc?start=1696',],uploadDate: '2024/07/27'},
        {artist: 'ウマ娘',song: 'ユメヲカケル!',youtubeLinks: ['https://www.youtube.com/embed/tjOawBPYPV8?start=685','https://www.youtube.com/embed/IXqpbXYPpBc?start=285','https://www.youtube.com/embed/6YKd3eLnYFY?start=397',],uploadDate: '2023/06/22'},
        {artist: 'けものフレンズ',song: 'ようこそジャパリパークへ',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=4880','https://www.youtube.com/embed/NOirh8vHd2I?start=2669','https://www.youtube.com/embed/6YKd3eLnYFY?start=2958',],uploadDate: '2023/06/13'},
        {artist: "May'n/中島愛 - マクロス",song: 'ライオン',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=6894','https://www.youtube.com/embed/bFIhXKqst4E?start=2376','https://www.youtube.com/embed/LMA1d775Qpk?start=7268',],uploadDate: '2023/06/29'},
        {artist: 'Mrs. GREEN APPLE',song: 'ライラック',youtubeLinks: ['https://www.youtube.com/embed/-9EbEyxBdxc?start=3444','https://www.youtube.com/embed/wZNw01A2ZPU?start=3760',],uploadDate: '2024/05/16'},
        {artist: 'ボカロ',song: 'ラヴィ',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=947','https://www.youtube.com/embed/WmAQDaz2Lew?start=1406','https://www.youtube.com/embed/dmNa1uamvDc?start=1790',],uploadDate: '2023/06/13'},
        {artist: 'ボカロ',song: 'ラヴィット',youtubeLinks: ['https://www.youtube.com/embed/TUvA7zIr1KM?start=6993',],uploadDate: '2024/02/27'},
        {artist: 'ボカロ',song: 'ラビットホール',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=1797','https://www.youtube.com/embed/NOirh8vHd2I?start=638',],uploadDate: '2023/06/13'},
        {artist: '松谷祐子 - うる星やつら',song: 'ラムのラブソング',youtubeLinks: ['https://www.youtube.com/embed/pS2dYFRWMuU?start=1834',],uploadDate: '2024/05/09'},
        {artist: 'その他',song: 'らららコッペパン',youtubeLinks: ['https://www.youtube.com/embed/m101bPhdXKA?start=7290',],uploadDate: '2024/04/08'},
        {artist: 'ボカロ',song: 'リグレットメッセージ',youtubeLinks: ['https://www.youtube.com/embed/td1q0jB1olk?start=3964',],uploadDate: '2024/03/13'},
        {artist: '米津玄師',song: 'リビングデッド・ユース',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=755','https://www.youtube.com/embed/Lh2rxl1lWyI?start=6001',],uploadDate: '2023/05/19'},
        {artist: 'ボカロ',song: 'リンネ',youtubeLinks: ['https://www.youtube.com/embed/2FSuC3sF7AY?start=3185',],uploadDate: '2024/10/02'},
        {artist: 'ボカロ',song: 'ルカルカナイトフィーバー',youtubeLinks: ['https://www.youtube.com/embed/TUvA7zIr1KM?start=6532',],uploadDate: '2024/02/27'},
        {artist: 'ボカロ',song: 'ロミオとシンデレラ',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=417','https://www.youtube.com/embed/cpMWJrh1t-k?start=1513',],uploadDate: '2023/04/17'},
        {artist: 'ボカロ',song: 'ワールドイズマイン',youtubeLinks: ['https://www.youtube.com/embed/BUDtEGiLhMw?start=2130',],uploadDate: '2024/01/24'},
        {artist: 'Ado',song: '阿修羅ちゃん',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=438','https://www.youtube.com/embed/DlJV7X5Wn90?start=474','https://www.youtube.com/embed/itTI_e9fSPY?start=2787',],uploadDate: '2023/06/13'},
        {artist: "u's - ラブライブ",song: '愛してるばんざーい',youtubeLinks: ['https://www.youtube.com/embed/MGsqoEivfO4?start=4960','https://www.youtube.com/embed/M95USmsYFO0?start=6938',],uploadDate: '2023/03/28'},
        {artist: 'Superfly',song: '愛をこめて花束を',youtubeLinks: ['https://www.youtube.com/embed/IXqpbXYPpBc?start=3407','https://www.youtube.com/embed/-9EbEyxBdxc?start=302',],uploadDate: '2024/01/11'},
        {artist: 'ボカロ',song: '悪ノ召使',youtubeLinks: ['https://www.youtube.com/embed/ep2iRkJXY-4?start=2600',],uploadDate: '2024/02/05'},
        {artist: 'ボカロ',song: '悪ノ娘',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=2313','https://www.youtube.com/embed/ep2iRkJXY-4?start=2142',],uploadDate: '2023/04/17'},
        {artist: 'King Gnu - 呪術廻戦',song: '一途',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=1438','https://www.youtube.com/embed/0EYG1N-wegA?start=4185','https://www.youtube.com/embed/dmNa1uamvDc?start=1486',],uploadDate: '2023/06/09'},
        {artist: 'ボカロ',song: '右肩の蝶',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=934',],uploadDate: '2023/04/17'},
        {artist: 'LiSA - 鬼滅の刃',song: '炎',youtubeLinks: ['https://www.youtube.com/embed/pS2dYFRWMuU?start=6763','https://www.youtube.com/embed/4uzfey2EOTc?start=8022',],uploadDate: '2024/05/09'},
        {artist: '学園アイドルマスター',song: '仮装狂騒曲',youtubeLinks: ['https://www.youtube.com/embed/wl2b0DRtLE0?start=2430','https://www.youtube.com/embed/NavZce1Abng?start=6044',],uploadDate: '2024/11/27'},
        {artist: '早見沙織 - HoneyWorks',song: '可愛くてごめん',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=9082','https://www.youtube.com/embed/eALWj0vtpYQ?start=3627',],uploadDate: '2023/06/01'},
        {artist: "JITTERIN'JINN - Whiteberry",song: '夏祭り',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=6505','https://www.youtube.com/embed/BPTPA6mBPOM?start=3425','https://www.youtube.com/embed/ZvC5W5wPHAM?start=5241',],uploadDate: '2023/06/29'},
        {artist: "u's - ラブライブ",song: '夏色えがおで1,2,Jump!',youtubeLinks: ['https://www.youtube.com/embed/M95USmsYFO0?start=6468','https://www.youtube.com/embed/BPTPA6mBPOM?start=2579','https://www.youtube.com/embed/LMA1d775Qpk?start=6254',],uploadDate: '2023/04/14'},
        {artist: '緑黄色社会 - 薬屋のひとりごと',song: '花になって',youtubeLinks: ['https://www.youtube.com/embed/Rfgv8LV1_3A?start=1075','https://www.youtube.com/embed/td1q0jB1olk?start=521','https://www.youtube.com/embed/MGlP_G5zu0I?start=851',],uploadDate: '2023/12/10'},
        {artist: 'ヨルシカ',song: '花に亡霊',youtubeLinks: ['https://www.youtube.com/embed/IXqpbXYPpBc?start=679','https://www.youtube.com/embed/L0C7ddHFY8I?start=4099','https://www.youtube.com/embed/4YmHDjaNqxQ?start=1063',],uploadDate: '2024/01/11'},
        {artist: 'さユり - リコリス・リコイル',song: '花の塔',youtubeLinks: ['https://www.youtube.com/embed/G7eO7CrCnXY?start=318',],uploadDate: '2023/09/14'},
        {artist: 'ハナヤマタ',song: '花ハ踊レヤいろはにほ',youtubeLinks: ['https://www.youtube.com/embed/VsFaoOFt0_0?start=5560','https://www.youtube.com/embed/MGlP_G5zu0I?start=160','https://www.youtube.com/embed/NavZce1Abng?start=615',],uploadDate: '2023/08/05'},
        {artist: 'AKB48',song: '会いたかった',youtubeLinks: ['https://www.youtube.com/embed/wpv_uWc3HGg?start=1751',],uploadDate: '2024/05/16'},
        {artist: '機巧少女は傷つかない',song: '回レ!雪月花',youtubeLinks: ['https://www.youtube.com/embed/NavZce1Abng?start=3963',],uploadDate: '2024/12/03'},
        {artist: 'Vaundy',song: '怪獣の花唄',youtubeLinks: ['https://www.youtube.com/embed/9Fj9vYgzL6c?start=2338','https://www.youtube.com/embed/dmNa1uamvDc?start=2050','https://www.youtube.com/embed/wl2b0DRtLE0?start=3298',],uploadDate: '2023/07/29'},
        {artist: 'YOASOBI - BEASTARS',song: '怪物',youtubeLinks: ['https://www.youtube.com/embed/UjTKs05Icag?start=3208','https://www.youtube.com/embed/DlJV7X5Wn90?start=5964',],uploadDate: '2023/05/09'},
        {artist: '桐谷健太',song: '海の声',youtubeLinks: ['https://www.youtube.com/embed/dHWhaC2nexg?start=3131',],uploadDate: '2024/09/10'},
        {artist: '藤岡藤巻-大橋のぞみ',song: '崖の上のポニョ',youtubeLinks: ['https://www.youtube.com/embed/WmAQDaz2Lew?start=7713','https://www.youtube.com/embed/dHWhaC2nexg?start=4099',],uploadDate: '2023/10/24'},
        {artist: '米津玄師',song: '感電',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=5152',],uploadDate: '2023/05/19'},
        {artist: '椎名林檎',song: '丸ノ内サディスティック',youtubeLinks: ['https://www.youtube.com/embed/L0C7ddHFY8I?start=5823',],uploadDate: '2024/03/18'},
        {artist: 'いきものがかり',song: '気まぐれロマンティック',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=5011','https://www.youtube.com/embed/kgRYm7SUMqM?start=1907','https://www.youtube.com/embed/_rAdBgHFFjU?start=276',],uploadDate: '2023/06/01'},
        {artist: "u's - ラブライブ",song: '輝夜の城で踊りたい',youtubeLinks: ['https://www.youtube.com/embed/M95USmsYFO0?start=1774','https://www.youtube.com/embed/eALWj0vtpYQ?start=2095','https://www.youtube.com/embed/Lh2rxl1lWyI?start=3962',],uploadDate: '2023/04/14'},
        {artist: 'Ado',song: '逆光',youtubeLinks: ['https://www.youtube.com/embed/pS2dYFRWMuU?start=5557',],uploadDate: '2024/05/09'},
        {artist: 'King Gnu - 呪術廻戦',song: '逆夢',youtubeLinks: ['https://www.youtube.com/embed/itTI_e9fSPY?start=9403',],uploadDate: '2023/12/01'},
        {artist: 'ボカロ',song: '強風オールバック',youtubeLinks: ['https://www.youtube.com/embed/itTI_e9fSPY?start=6876','https://www.youtube.com/embed/GEQLbX0qVmY?start=6614','https://www.youtube.com/embed/TUvA7zIr1KM?start=5541',],uploadDate: '2023/12/01'},
        {artist: 'その他',song: '君が代',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=2305',],uploadDate: '2023/06/29'},
        {artist: '湊あくあ - Vtuber',song: '君の最推しにしてよ!',youtubeLinks: ['https://www.youtube.com/embed/JUZ_ABhOoDM?start=574','https://www.youtube.com/embed/Lh2rxl1lWyI?start=7722',],uploadDate: '2024/10/26'},
        {artist: 'supercell - 物語シリーズ',song: '君の知らない物語',youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=6988','https://www.youtube.com/embed/MAcwKdfs5qQ?start=4050','https://www.youtube.com/embed/B4QjGk-20OI?start=1273',],uploadDate: '2023/04/10'},
        {artist: 'YOASOBI',song: '群青',youtubeLinks: ['https://www.youtube.com/embed/DlJV7X5Wn90?start=7475','https://www.youtube.com/embed/TUvA7zIr1KM?start=8524','https://www.youtube.com/embed/B4QjGk-20OI?start=5590',],uploadDate: '2023/10/17'},
        {artist: 'ボカロ',song: '結ンデ開イテ羅刹ト骸',youtubeLinks: ['https://www.youtube.com/embed/WmAQDaz2Lew?start=2382','https://www.youtube.com/embed/2FSuC3sF7AY?start=4005',],uploadDate: '2023/10/24'},
        {artist: "u's - ラブライブ",song: '孤独なHeaven',youtubeLinks: ['https://www.youtube.com/embed/urwa-ef1KOw?start=3871',],uploadDate: '2024/03/27'},
        {artist: '湊あくあ - Vtuber',song: '誇り高きアイドル',youtubeLinks: ['https://www.youtube.com/embed/JUZ_ABhOoDM?start=920','https://www.youtube.com/embed/Lh2rxl1lWyI?start=3101',],uploadDate: '2024/10/26'},
        {artist: 'Linked Horizon - 進撃の巨人',song: '紅蓮の弓矢',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=885','https://www.youtube.com/embed/-9EbEyxBdxc?start=1301',],uploadDate: '2023/06/09'},
        {artist: 'LiSA - 鬼滅の刃',song: '紅蓮華',youtubeLinks: ['https://www.youtube.com/embed/UjTKs05Icag?start=6952','https://www.youtube.com/embed/4Jrfzxmt3Z8?start=12875','https://www.youtube.com/embed/4YmHDjaNqxQ?start=711',],uploadDate: '2023/05/09'},
        {artist: 'ももいろクローバーZ',song: '行くぜっ！怪盗少女',youtubeLinks: ['https://www.youtube.com/embed/pNj4jJbUW4o?start=4233',],uploadDate: '2024/02/21'},
        {artist: 'Supercell',song: '告白',youtubeLinks: ['https://www.youtube.com/embed/bFIhXKqst4E?start=4597','https://www.youtube.com/embed/td1q0jB1olk?start=1302',],uploadDate: '2023/12/19'},
        {artist: 'ボカロ',song: '混沌ブギ',youtubeLinks: ['https://www.youtube.com/embed/pNj4jJbUW4o?start=874','https://www.youtube.com/embed/L0C7ddHFY8I?start=1059',],uploadDate: '2024/02/21'},
        {artist: '高橋洋子 - 新世紀エヴァンゲリオン',song: '魂のルフラン',youtubeLinks: ['https://www.youtube.com/embed/LMA1d775Qpk?start=1009',],uploadDate: '2024/10/15'},
        {artist: 'ボカロ',song: '砂の惑星',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=2873',],uploadDate: '2023/06/29'},
        {artist: 'ボカロ',song: '鎖の少女',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=4067','https://www.youtube.com/embed/bFIhXKqst4E?start=2410','https://www.youtube.com/embed/m101bPhdXKA?start=854',],uploadDate: '2023/04/17'},
        {artist: 'Aimer - 鬼滅の刃',song: '残響散歌',youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=786','https://www.youtube.com/embed/BUDtEGiLhMw?start=1110','https://www.youtube.com/embed/wZNw01A2ZPU?start=2005',],uploadDate: '2023/04/10'},
        {artist: '高橋洋子 - 新世紀エヴァンゲリオン',song: '残酷な天使のテーゼ',youtubeLinks: ['https://www.youtube.com/embed/aNLxjnSPbQE?start=2621','https://www.youtube.com/embed/dmNa1uamvDc?start=1121','https://www.youtube.com/embed/LMA1d775Qpk?start=380',],uploadDate: '2023/06/09'},
        {artist: 'Ado - ワンピース',song: '私は最強',youtubeLinks: ['https://www.youtube.com/embed/eALWj0vtpYQ?start=4968','https://www.youtube.com/embed/Snfv7YDOjUE?start=225','https://www.youtube.com/embed/WXIN8Ip0X10?start=482',],uploadDate: '2023/09/21'},
        {artist: 'その他',song: '手のひらを太陽に',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=6117',],uploadDate: '2023/06/29'},
        {artist: 'しぐれうい - Vtuber',song: '粛聖!!ロリ神レクイエム☆',youtubeLinks: ['https://www.youtube.com/embed/kgRYm7SUMqM?start=384','https://www.youtube.com/embed/pNj4jJbUW4o?start=228','https://www.youtube.com/embed/VpkfTbqCy_Y?start=2347',],uploadDate: '2023/10/05'},
        {artist: '米津玄師',song: '春雷',youtubeLinks: ['https://www.youtube.com/embed/7SPpO1RkmxU?start=4306',],uploadDate: '2023/05/19'},
        {artist: "u's - ラブライブ",song: '純愛レンズ',youtubeLinks: ['https://www.youtube.com/embed/urwa-ef1KOw?start=4897',],uploadDate: '2024/03/27'},
        {artist: 'ゴールデンボンバー',song: '女々しくて',youtubeLinks: ['https://www.youtube.com/embed/NOirh8vHd2I?start=4485',],uploadDate: '2024/01/29'},
        {artist: 'Ado',song: '唱',youtubeLinks: ['https://www.youtube.com/embed/kgRYm7SUMqM?start=6755','https://www.youtube.com/embed/ROxeYUG6J8A?start=1620','https://www.youtube.com/embed/Lh2rxl1lWyI?start=7337',],uploadDate: '2023/10/05'},
        {artist: 'ボカロ',song: '少女レイ',youtubeLinks: ['https://www.youtube.com/embed/BPTPA6mBPOM?start=762','https://www.youtube.com/embed/itTI_e9fSPY?start=3573','https://www.youtube.com/embed/BUDtEGiLhMw?start=640',],uploadDate: '2023/07/13'},
        {artist: '井上陽水',song: '少年時代',youtubeLinks: ['https://www.youtube.com/embed/BPTPA6mBPOM?start=2134',],uploadDate: '2023/07/13'},
        {artist: "u's - ラブライブ",song: '硝子の花園',youtubeLinks: ['https://www.youtube.com/embed/Sy04TSlMgs8?start=2957',],uploadDate: '2024/04/03'},
        {artist: 'ボカロ',song: '寝起きヤシの木',youtubeLinks: ['https://www.youtube.com/embed/cpMWJrh1t-k?start=2740','https://www.youtube.com/embed/4Jrfzxmt3Z8?start=2896',],uploadDate: '2023/11/09'},
        {artist: 'Ado',song: '心という名の不可解',youtubeLinks: ['https://www.youtube.com/embed/bFIhXKqst4E?start=373',],uploadDate: '2023/12/19'},
        {artist: 'ロードオブメジャー',song: '心絵',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=3530','https://www.youtube.com/embed/eALWj0vtpYQ?start=7428','https://www.youtube.com/embed/QPusrCYYy3c?start=1499',],uploadDate: '2023/06/13'},
        {artist: 'ボカロ',song: '心拍数#08ZZ',youtubeLinks: ['https://www.youtube.com/embed/MGsqoEivfO4?start=3178',],uploadDate: '2023/03/28'},
        {artist: 'Ado - ワンピース',song: '新時代',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=5430','https://www.youtube.com/embed/eALWj0vtpYQ?start=810','https://www.youtube.com/embed/Snfv7YDOjUE?start=746',],uploadDate: '2023/06/29'},
        {artist: 'ボカロ',song: '神っぽいな',youtubeLinks: ['https://www.youtube.com/embed/qnvZhVYoEpM?start=1447','https://www.youtube.com/embed/Snfv7YDOjUE?start=2058','https://www.youtube.com/embed/B4QjGk-20OI?start=4399',],uploadDate: '2023/04/10'},
        {artist: 'ボカロ',song: '人柱アリス',youtubeLinks: ['https://www.youtube.com/embed/td1q0jB1olk?start=3068',],uploadDate: '2024/03/13'},
        {artist: 'Back number',song: '水平線',youtubeLinks: ['https://www.youtube.com/embed/DlJV7X5Wn90?start=4912','https://www.youtube.com/embed/HejWiGIA2rQ?start=3826','https://www.youtube.com/embed/wl2b0DRtLE0?start=4152',],uploadDate: '2023/10/17'},
        {artist: 'ボカロ',song: '酔いどれ知らず',youtubeLinks: ['https://www.youtube.com/embed/itTI_e9fSPY?start=6513','https://www.youtube.com/embed/ep2iRkJXY-4?start=1505','https://www.youtube.com/embed/Lh2rxl1lWyI?start=2739',],uploadDate: '2023/12/01'},
        {artist: 'SMAP',song: '世界に一つだけの花',youtubeLinks: ['https://www.youtube.com/embed/MGlP_G5zu0I?start=1558',],uploadDate: '2024/11/30'},
        {artist: '学マス - アイマス',song: '世界一可愛い私',youtubeLinks: ['https://www.youtube.com/embed/VpkfTbqCy_Y?start=2943',],uploadDate: '2024/09/24'},
        {artist: 'ナナシス',song: '星屑☆シーカー',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=2873',],uploadDate: '2024/04/18'},
        {artist: 'ヨルシカ - 葬送のフリーレン',song: '晴る',youtubeLinks: ['https://www.youtube.com/embed/TUvA7zIr1KM?start=351','https://www.youtube.com/embed/9qJ_Ec2YxSk?start=1733','https://www.youtube.com/embed/4Jrfzxmt3Z8?start=5366',],uploadDate: '2024/02/27'},
        {artist: 'ALI PROJECT - ローゼンメイデン',song: '聖少女領域',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=1859','https://www.youtube.com/embed/WXIN8Ip0X10?start=3282','https://www.youtube.com/embed/4uzfey2EOTc?start=4008',],uploadDate: '2023/06/01'},
        {artist: 'Aqours - ラブライブ',song: '青空jumping heart',youtubeLinks: ['https://www.youtube.com/embed/M95USmsYFO0?start=3014',],uploadDate: '2023/04/14'},
        {artist: '松田聖子',song: '赤いスイートピー',youtubeLinks: ['https://www.youtube.com/embed/dHWhaC2nexg?start=2262',],uploadDate: '2024/09/10'},
        {artist: 'ボカロ',song: '千本桜',youtubeLinks: ['https://www.youtube.com/embed/eALWj0vtpYQ?start=2825','https://www.youtube.com/embed/4Jrfzxmt3Z8?start=1741','https://www.youtube.com/embed/NavZce1Abng?start=3395',],uploadDate: '2023/09/21'},
        {artist: '這いよれ! ニャル子さん',song: '太陽曰く燃えよカオス',youtubeLinks: ['https://www.youtube.com/embed/UjTKs05Icag?start=2510','https://www.youtube.com/embed/BUDtEGiLhMw?start=3783','https://www.youtube.com/embed/ZvC5W5wPHAM?start=2918',],uploadDate: '2023/05/09'},
        {artist: 'DAOKO - 米津玄師',song: '打上花火',youtubeLinks: ['https://www.youtube.com/embed/4uzfey2EOTc?start=7367',],uploadDate: '2024/12/20'},
        {artist: '東山奈央 - HoneyWorks',song: '男の子の目的は何？',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=5159','https://www.youtube.com/embed/DlJV7X5Wn90?start=6969',],uploadDate: '2023/06/05'},
        {artist: '中島みゆき',song: '地上の星',youtubeLinks: ['https://www.youtube.com/embed/td1q0jB1olk?start=4871',],uploadDate: '2024/03/13'},
        {artist: 'Aimer',song: '蝶々結び',youtubeLinks: ['https://www.youtube.com/embed/LMA1d775Qpk?start=3496',],uploadDate: '2024/10/15'},
        {artist: 'Lia',song: '鳥の詩',youtubeLinks: ['https://www.youtube.com/embed/2FSuC3sF7AY?start=5282',],uploadDate: '2024/10/02'},
        {artist: '石川さゆり',song: '津軽海峡・冬景色',youtubeLinks: ['https://www.youtube.com/embed/m101bPhdXKA?start=4013',],uploadDate: '2024/04/08'},
        {artist: 'ボカロ',song: '天ノ弱',youtubeLinks: ['https://www.youtube.com/embed/2bNX7OV8iK4?start=7346',],uploadDate: '2023/04/17'},
        {artist: 'BUMP OF CHICKEN',song: '天体観測',youtubeLinks: ['https://www.youtube.com/embed/DlJV7X5Wn90?start=1416','https://www.youtube.com/embed/QPusrCYYy3c?start=2088',],uploadDate: '2023/10/17'},
        {artist: 'serial TV drama - 銀魂',song: '桃源郷エイリアン',youtubeLinks: ['https://www.youtube.com/embed/ROxeYUG6J8A?start=4622',],uploadDate: '2024/03/04'},
        {artist: 'EXILE',song: '道',youtubeLinks: ['https://www.youtube.com/embed/TUvA7zIr1KM?start=8228',],uploadDate: '2024/02/27'},
        {artist: 'いきものがかり - 七つの大罪',song: '熱情のスペクトラム',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=5460','https://www.youtube.com/embed/bFIhXKqst4E?start=1960',],uploadDate: '2023/06/13'},
        {artist: '学マス - アイマス',song: '白線',youtubeLinks: ['https://www.youtube.com/embed/dHWhaC2nexg?start=267',],uploadDate: '2024/09/10'},
        {artist: 'King Gnu',song: '白日',youtubeLinks: ['https://www.youtube.com/embed/DlJV7X5Wn90?start=6486','https://www.youtube.com/embed/Rfgv8LV1_3A?start=6123','https://www.youtube.com/embed/L0C7ddHFY8I?start=8527',],uploadDate: '2023/10/17'},
        {artist: 'tuki. - マッシュル',song: '晩餐歌',youtubeLinks: ['https://www.youtube.com/embed/L0C7ddHFY8I?start=3953','https://www.youtube.com/embed/m101bPhdXKA?start=342',],uploadDate: '2024/03/18'},
        {artist: "u's - ラブライブ",song: '微熱からMystery',youtubeLinks: ['https://www.youtube.com/embed/urwa-ef1KOw?start=5315','https://www.youtube.com/embed/rDor8WLUz3k?start=1498',],uploadDate: '2024/03/27'},
        {artist: '宝鐘マリン - Vtuber',song: '美少女無罪♡パイレーツ',youtubeLinks: ['https://www.youtube.com/embed/G7eO7CrCnXY?start=2191','https://www.youtube.com/embed/cpMWJrh1t-k?start=952','https://www.youtube.com/embed/JUZ_ABhOoDM?start=1300',],uploadDate: '2023/09/14'},
        {artist: '戦姫絶唱シンフォギア',song: '不死鳥のフランメ',youtubeLinks: ['https://www.youtube.com/embed/urwa-ef1KOw?start=2333','https://www.youtube.com/embed/Sy04TSlMgs8?start=3980',],uploadDate: '2024/03/27'},
        {artist: "u's - ラブライブ",song: '僕らは今のなかで',youtubeLinks: ['https://www.youtube.com/embed/M95USmsYFO0?start=1238','https://www.youtube.com/embed/WXIN8Ip0X10?start=2870',],uploadDate: '2023/04/14'},
        {artist: 'ナナシス',song: '僕らは青空になる',youtubeLinks: ['https://www.youtube.com/embed/0SpDxwXYsEM?start=8068',],uploadDate: '2024/04/18'},
        {artist: 'ボカロ',song: '魔法少女とチョコレゐト',youtubeLinks: ['https://www.youtube.com/embed/m101bPhdXKA?start=5625',],uploadDate: '2024/04/08'},
        {artist: 'Aqours - ラブライブ',song: '未来の僕らは知ってるよ',youtubeLinks: ['https://www.youtube.com/embed/AmxKWJq9Utc?start=683',],uploadDate: '2024/07/27'},
        {artist: 'ドラえもん',song: '夢をかなえてドラえもん',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=1537',],uploadDate: '2023/06/05'},
        {artist: 'EGOIST',song: '名前のない怪物',youtubeLinks: ['https://www.youtube.com/embed/UjTKs05Icag?start=1564','https://www.youtube.com/embed/mADbrQhuOik?start=3359','https://www.youtube.com/embed/pS2dYFRWMuU?start=1209',],uploadDate: '2023/05/09'},
        {artist: 'ももいろクローバーZ',song: '猛烈宇宙交響曲・第七楽章「無限の愛」',youtubeLinks: ['https://www.youtube.com/embed/pNj4jJbUW4o?start=5143',],uploadDate: '2024/02/21'},
        {artist: 'YOASOBI',song: '夜に駆ける',youtubeLinks: ['https://www.youtube.com/embed/9Fj9vYgzL6c?start=9903','https://www.youtube.com/embed/itTI_e9fSPY?start=7334','https://www.youtube.com/embed/0EYG1N-wegA?start=2411',],uploadDate: '2023/07/29'},
        {artist: '光GENJI',song: '勇気100%',youtubeLinks: ['https://www.youtube.com/embed/MAcwKdfs5qQ?start=945',],uploadDate: '2023/12/29'},
        {artist: "u's - ラブライブ",song: '勇気のReason',youtubeLinks: ['https://www.youtube.com/embed/wZNw01A2ZPU?start=2357',],uploadDate: '2024/06/11'},
        {artist: 'YOASOBI - 葬送のフリーレン',song: '勇者',youtubeLinks: ['https://www.youtube.com/embed/itTI_e9fSPY?start=343','https://www.youtube.com/embed/Snfv7YDOjUE?start=3054','https://www.youtube.com/embed/td1q0jB1olk?start=4368',],uploadDate: '2023/12/01'},
        {artist: 'Ado',song: '踊',youtubeLinks: ['https://www.youtube.com/embed/FiSuJ3tVZzU?start=5990','https://www.youtube.com/embed/pNj4jJbUW4o?start=5715',],uploadDate: '2023/06/13'},
        {artist: '藍井エイル',song: '翼',youtubeLinks: ['https://www.youtube.com/embed/pS2dYFRWMuU?start=6327','https://www.youtube.com/embed/2FSuC3sF7AY?start=6747',],uploadDate: '2024/05/09'},
        {artist: 'その他',song: '翼をください',youtubeLinks: ['https://www.youtube.com/embed/NOirh8vHd2I?start=3238','https://www.youtube.com/embed/2FSuC3sF7AY?start=6330',],uploadDate: '2024/01/29'},
        {artist: 'ボカロ',song: '裏表ラバーズ',youtubeLinks: ['https://www.youtube.com/embed/-9EbEyxBdxc?start=3922',],uploadDate: '2024/05/16'},
        {artist: '星野源',song: '恋',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=7330','https://www.youtube.com/embed/K9ppwMaarKs?start=2758','https://www.youtube.com/embed/L0C7ddHFY8I?start=6986',],uploadDate: '2023/06/29'},
        {artist: 'きらりん☆レボリューション',song: '恋☆カナ',youtubeLinks: ['https://www.youtube.com/embed/E_gzQSl55W4?start=3401',],uploadDate: '2024/05/23'},
        {artist: 'AKB48',song: '恋するフォーチュンクッキー',youtubeLinks: ['https://www.youtube.com/embed/FMDmiPACEi4?start=3508','https://www.youtube.com/embed/kgRYm7SUMqM?start=4127',],uploadDate: '2023/06/05'},
        {artist: 'Aqours - ラブライブ',song: '恋になりたいAQUARIUM',youtubeLinks: ['https://www.youtube.com/embed/BPTPA6mBPOM?start=1404','https://www.youtube.com/embed/B4QjGk-20OI?start=774',],uploadDate: '2023/07/13'},
        {artist: '這いよれ! ニャル子さん',song: '恋は渾沌の隷也',youtubeLinks: ['https://www.youtube.com/embed/mADbrQhuOik?start=9390','https://www.youtube.com/embed/cpMWJrh1t-k?start=5585',],uploadDate: '2023/06/29'},
        {artist: '物語シリーズ',song: '恋愛サーキュレーション',youtubeLinks: ['https://www.youtube.com/embed/jl2s538rDGw?start=3283','https://www.youtube.com/embed/Snfv7YDOjUE?start=2488','https://www.youtube.com/embed/4uzfey2EOTc?start=3279',],uploadDate: '2023/06/01'},
        {artist: 'ボカロ',song: '六兆年と一夜物語',youtubeLinks: ['https://www.youtube.com/embed/pS2dYFRWMuU?start=3460',],uploadDate: '2024/05/09'},
    ];
}
